<?php
require_once('fpdf/fpdf.php');

// Input validation
if (!isset($_GET['type']) || !in_array($_GET['type'], ['all', 'approved', 'pending', 'rejected', 'closed'])) {
    echo json_encode(['error' => 'Invalid report type']);
    exit();
}

$report_type = $_GET['type'];

// Mock admin data (as you provided)
$mockAdmins = [
    [
        'full_name' => 'Jerome Malunes',
        'email' => 'jeromemalunes@gmail.com',
        'password' => password_hash('admin123', PASSWORD_DEFAULT),
        'role' => 'admin',
        'loan_officer_id' => 'LO-0123'
    ]
];
$current_admin = $mockAdmins[0];

// Database connection
$host = "localhost";
$user = "root";
$pass = "";
$db = "bankingdb";
$conn = new mysqli($host, $user, $pass, $db);
if ($conn->connect_error) {
    echo json_encode(['error' => 'DB error: ' . $conn->connect_error]);
    exit();
}

// Build WHERE clause
$where_clause = '';
switch ($report_type) {
    case 'approved': $where_clause = "WHERE status = 'Approved'"; break;
    case 'pending': $where_clause = "WHERE status = 'Pending'"; break;
    case 'rejected': $where_clause = "WHERE status = 'Rejected'"; break;
    case 'closed': $where_clause = "WHERE status = 'Closed'"; break;
    // 'all' → no WHERE
}

// Fetch loans
$sql = "SELECT 
    id AS client_id,
    full_name AS client_name,
    loan_type,
    loan_amount,
    loan_terms,
    monthly_payment,
    status,
    created_at,
    next_payment_due,
    due_date
FROM loan_applications 
$where_clause 
ORDER BY created_at DESC";

$result = $conn->query($sql);
$loans = [];
if ($result) {
    while ($row = $result->fetch_assoc()) {
        $loans[] = $row;
    }
}
$conn->close();

// ✅ COUNT loans by status for Notes section
$counts = ['Approved' => 0, 'Pending' => 0, 'Rejected' => 0, 'Closed' => 0];
foreach ($loans as $loan) {
    $status = ucfirst(strtolower(trim($loan['status'])));
    if (array_key_exists($status, $counts)) {
        $counts[$status]++;
    }
}

// Generate PDF
$pdf = new FPDF('L', 'mm', 'A4');
$pdf->AddPage();
$pdf->SetFont('Arial', 'B', 16);

// Header
$pdf->Cell(0, 15, 'EVERGREEN TRUST AND SAVINGS LOAN SERVICES', 0, 1, 'C');
$pdf->Ln(5);

// Loan Officer Report Header
$pdf->SetFont('Arial', 'B', 14);
$pdf->Cell(0, 10, 'Loan Officer Report (Monthly)', 0, 1, 'L');
$pdf->SetFont('Arial', '', 10);
$pdf->Cell(0, 8, 'Reporting Period: ' . date('F Y'), 0, 1, 'L');
$pdf->Cell(0, 8, 'Prepared by: Loan Officer - ' . $current_admin['full_name'], 0, 1, 'L');
$pdf->Cell(0, 8, 'Department: Loan Subsystem', 0, 1, 'L');
$pdf->Ln(10);

// Table header
$pdf->SetFont('Arial', 'B', 10);
$pdf->SetFillColor(200, 200, 200);
$w = [25, 40, 35, 30, 30, 35, 35, 35, 25];
$header = ['Client ID','Client Name','Loan Type','Loan Amount','Term','Monthly Payment','Total Paid','Remaining Balance','Status'];
for ($i = 0; $i < count($header); $i++) {
    $pdf->Cell($w[$i], 8, $header[$i], 1, 0, 'C', true);
}
$pdf->Ln();

// Table rows
$pdf->SetFont('Arial', '', 9);
foreach ($loans as $loan) {
    $loan_amount = number_format($loan['loan_amount'], 2);
    $monthly_payment = number_format($loan['monthly_payment'], 2);
    $total_paid = '0.00';
    $remaining_balance = $loan_amount;
    $status = ucfirst($loan['status']);
    
    $data = [
        $loan['client_id'],
        substr($loan['client_name'], 0, 25),
        $loan['loan_type'],
        'PHP ' . $loan_amount,
        $loan['loan_terms'],
        'PHP ' . $monthly_payment,
        'PHP ' . $total_paid,
        'PHP ' . $remaining_balance,
        $status
    ];

    for ($i = 0; $i < count($data); $i++) {
        $pdf->Cell($w[$i], 7, $data[$i], 1, 0, 'L');
    }
    $pdf->Ln();
}

// Notes section - NO BULLETS, NO SPECIAL CHARACTERS
$pdf->Ln(10);
$pdf->SetFont('Arial', 'B', 12);
$pdf->Cell(0, 10, 'Notes:', 0, 1);
$pdf->SetFont('Arial', '', 10);

$notes = [
    "Total Paid and Remaining Balance are based on current system records.",
    "This report was generated on " . date('F j, Y \a\t g:i A') . ".",
    "Approved Loans: " . $counts['Approved'],
    "Rejected Loans: " . $counts['Rejected'],
    "Pending Loans: " . $counts['Pending']
];

foreach ($notes as $note) {
    $pdf->MultiCell(0, 6, $note, 0, 'L');
}

// Footer
$pdf->SetY(-15);
$pdf->SetFont('Arial', 'I', 8);
$pdf->Cell(0, 10, 'Generated by Evergreen Trust and Savings - Page ' . $pdf->PageNo(), 0, 0, 'C');

// Save PDF
$uploadDir = 'uploads/';
if (!is_dir($uploadDir)) {
    mkdir($uploadDir, 0777, true);
}

$filename = "loan_report_{$report_type}_" . date('YmdHis') . ".pdf";
$fullPath = $uploadDir . $filename;
$pdf->Output('F', $fullPath);

echo json_encode(['success' => true, 'filename' => $fullPath]);
?>