<?php
require_once('fpdf/fpdf.php');

// Input validation
if (!isset($_GET['loan_id']) || !isset($_GET['type'])) {
    echo json_encode(['error' => 'Missing parameters']);
    exit();
}

$loan_id = intval($_GET['loan_id']);
$type = $_GET['type'];

if (!in_array($type, ['approved', 'rejected'])) {
    echo json_encode(['error' => 'Invalid type']);
    exit();
}

// Database connection
$host = "localhost";
$user = "root";
$pass = "";
$db = "bankingdb";
$conn = new mysqli($host, $user, $pass, $db);
if ($conn->connect_error) {
    echo json_encode(['error' => 'DB error: ' . $conn->connect_error]);
    exit();
}

// Fetch loan
$stmt = $conn->prepare("SELECT * FROM loan_applications WHERE id = ?");
$stmt->bind_param("i", $loan_id);
$stmt->execute();
$result = $stmt->get_result();

if (!$result || $result->num_rows === 0) {
    echo json_encode(['error' => 'Loan not found']);
    exit();
}

$loan = $result->fetch_assoc();
$stmt->close();
$conn->close();

// Create uploads directory if it doesn't exist
$uploadDir = 'uploads/';
if (!is_dir($uploadDir)) {
    mkdir($uploadDir, 0777, true);
}

// Generate PDF in LANDSCAPE orientation
$pdf = new FPDF('L', 'mm', 'A4');
$pdf->AddPage();
$pdf->SetAutoPageBreak(true, 25);

// Set font
$pdf->SetFont('Arial', '', 12);

// Header: Simple text (no circle)
$pdf->SetFont('Arial', 'B', 16);
$pdf->Cell(0, 15, 'EVERGREEN TRUST AND SAVINGS LOAN SERVICES', 0, 1, 'C');
$pdf->Ln(10);

// Main message
$pdf->SetFont('Arial', '', 12);
if ($type === 'approved') {
    $message = "Good day! {$loan['full_name']}! Your loan has been approved! Please make your payment on or before the due date to avoid penalties or additional charges.";
} else {
    $message = "Good day! {$loan['full_name']}! Your loan has been rejected! Because some of your documents are inaccurate. There are also missing documents that you need to comply with. Please upload accurate documents next time.";
}
$pdf->MultiCell(0, 8, $message, 0, 'L');
$pdf->Ln(10);

// Loan Details section
$pdf->SetFont('Arial', 'B', 12);
$pdf->Cell(0, 10, 'Loan Details:', 0, 1, 'L');
$pdf->SetFont('Arial', '', 12);

// Format loan details
$details = [
    'Loan Amount' => 'PHP ' . number_format($loan['loan_amount'], 2),
    'Loan Type' => $loan['loan_type'],
    'Term' => $loan['loan_terms'],
    'Interest' => '20% per annum',
    'Monthly Payment' => 'PHP ' . number_format($loan['monthly_payment'], 2),
    'Status' => ucfirst($loan['status'])
];

// Add Next Payment Due if approved
if ($type === 'approved' && $loan['next_payment_due']) {
    $details['Next Payment Due'] = date('M j, Y', strtotime($loan['next_payment_due']));
}

// Add Last Payment Date if approved
if ($type === 'approved' && $loan['due_date']) {
    $details['Last Payment'] = date('M j, Y', strtotime($loan['due_date']));
}

// Add Remarks
if ($type === 'approved') {
    $details['Remarks'] = $loan['remarks'] ?: 'None';
} else {
    $details['Remarks'] = $loan['rejection_remarks'] ?: 'None';
}

// Display loan details in a clean format
foreach ($details as $label => $value) {
    $pdf->Cell(50, 8, $label . ':', 0, 0, 'L');
    $pdf->Cell(0, 8, $value, 0, 1, 'L');
}

// Footer - added at bottom of current page
$pdf->SetY(-20);
$pdf->SetFont('Arial', 'I', 8);
$pdf->Cell(0, 10, 'Generated by Evergreen Trust and Savings - ' . date('Y-m-d H:i:s'), 0, 0, 'C');

// Save PDF
$filename = "loan_{$type}_{$loan_id}_" . date('YmdHis') . ".pdf";
$fullPath = $uploadDir . $filename;

try {
    $pdf->Output('F', $fullPath);
    if (file_exists($fullPath)) {
        echo json_encode(['success' => true, 'filename' => $fullPath]);
    } else {
        echo json_encode(['error' => 'File not created']);
    }
} catch (Exception $e) {
    echo json_encode(['error' => 'PDF error: ' . $e->getMessage()]);
}
?>